"""External validation helpers for comparing against ipole/grtrans-style outputs."""

from __future__ import annotations

from dataclasses import dataclass, asdict
import json
from pathlib import Path
import shutil
import subprocess
from typing import Mapping, Sequence

import numpy as np


@dataclass(frozen=True)
class IpoleRunConfig:
    dump_path: str
    output_path: str
    freq_hz: float = 230.0e9
    mbh_msun: float = 6.2e9
    m_unit_g: float = 1.0e25
    camera_theta_deg: float = 17.0
    camera_radius_m: float = 1000.0
    fov_muas: float = 160.0
    nx: int = 64
    ny: int = 64
    extra_parameters: Mapping[str, str | int | float] | None = None


def write_ipole_parameter_file(cfg: IpoleRunConfig, path: str | Path) -> Path:
    """Write a minimal ipole parameter file for a selected GRMHD dump."""

    params: dict[str, str | int | float] = {
        "dump": cfg.dump_path,
        "outfile": cfg.output_path,
        "freqcgs": cfg.freq_hz,
        "MBH": cfg.mbh_msun,
        "M_unit": cfg.m_unit_g,
        "thetacam": cfg.camera_theta_deg,
        "rcam": cfg.camera_radius_m,
        "fovx_dsource": cfg.fov_muas,
        "fovy_dsource": cfg.fov_muas,
        "nx": cfg.nx,
        "ny": cfg.ny,
    }
    if cfg.extra_parameters:
        params.update(cfg.extra_parameters)
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# Generated by blackhole_sim.external_validation.write_ipole_parameter_file"]
    lines.extend(f"{k} {v}" for k, v in params.items())
    p.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return p


def run_ipole(ipole_binary: str | Path, parameter_file: str | Path, timeout_s: int = 3600) -> subprocess.CompletedProcess[str]:
    """Run ipole with a parameter file. Requires a locally built ipole binary."""

    exe = shutil.which(str(ipole_binary)) or str(ipole_binary)
    if not Path(exe).exists() and shutil.which(exe) is None:
        raise FileNotFoundError(f"ipole binary not found: {ipole_binary}")
    return subprocess.run([exe, "-par", str(parameter_file)], check=True, text=True, capture_output=True, timeout=timeout_s)


def read_ipole_stokes_hdf5(path: str | Path, jy_per_pixel: bool = False) -> np.ndarray:
    """Read ipole HDF5 image output as an array with shape (NY, NX, 4).

    ipole stores ``pol`` as (NX, NY, 5), with I,Q,U,V,tauF. The returned array
    transposes to image row-major order and drops tauF. When ``jy_per_pixel`` is
    true, Stokes values are multiplied by /header/scale.
    """

    try:
        import h5py  # type: ignore
    except ImportError as exc:
        raise RuntimeError("h5py is required to read ipole HDF5 images") from exc
    with h5py.File(path, "r") as f:
        pol = np.asarray(f["pol"], dtype=float)[..., :4]
        scale = float(f["header/scale"][()]) if jy_per_pixel and "header/scale" in f else 1.0
    return np.transpose(pol, (1, 0, 2)) * scale


def read_our_stokes_npz(path: str | Path) -> np.ndarray:
    with np.load(path) as z:
        if "stokes" not in z:
            raise KeyError(f"{path} does not contain a 'stokes' array")
        return np.asarray(z["stokes"], dtype=float)


@dataclass(frozen=True)
class StokesComparisonMetrics:
    shape: tuple[int, int, int]
    max_abs: float
    mean_abs: float
    rel_l1: float
    i_flux_a: float
    i_flux_b: float
    q_flux_a: float
    q_flux_b: float
    u_flux_a: float
    u_flux_b: float
    v_flux_a: float
    v_flux_b: float
    passed: bool

    def to_json_dict(self) -> dict[str, object]:
        return asdict(self)


def compare_stokes_images(
    a: np.ndarray,
    b: np.ndarray,
    *,
    rtol_l1: float = 0.2,
    atol_max: float | None = None,
) -> StokesComparisonMetrics:
    """Compare two Stokes image cubes after enforcing identical shape."""

    aa = np.asarray(a, dtype=float)
    bb = np.asarray(b, dtype=float)
    if aa.shape != bb.shape:
        raise ValueError(f"shape mismatch: {aa.shape} != {bb.shape}")
    diff = aa - bb
    denom = float(np.sum(np.abs(bb)) + 1.0e-300)
    max_abs = float(np.max(np.abs(diff)))
    rel_l1 = float(np.sum(np.abs(diff)) / denom)
    passed = rel_l1 <= rtol_l1 and (atol_max is None or max_abs <= atol_max)
    flux_a = np.sum(aa, axis=(0, 1))
    flux_b = np.sum(bb, axis=(0, 1))
    return StokesComparisonMetrics(
        shape=tuple(int(x) for x in aa.shape),
        max_abs=max_abs,
        mean_abs=float(np.mean(np.abs(diff))),
        rel_l1=rel_l1,
        i_flux_a=float(flux_a[0]),
        i_flux_b=float(flux_b[0]),
        q_flux_a=float(flux_a[1]),
        q_flux_b=float(flux_b[1]),
        u_flux_a=float(flux_a[2]),
        u_flux_b=float(flux_b[2]),
        v_flux_a=float(flux_a[3]),
        v_flux_b=float(flux_b[3]),
        passed=passed,
    )


def write_comparison_report(metrics: StokesComparisonMetrics, path: str | Path) -> Path:
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(metrics.to_json_dict(), indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return p
