// v0.7 CUDA hot-loop port for offline Kerr + coefficient-brick Stokes rendering.
// One thread = one pixel. Coefficients are flattened as [nr][nt][np][11].
#include <math.h>
struct State6 { float t,r,th,ph,pr,pth; };
struct Mat4 { float m[16]; };
__device__ float mget(const Mat4& m,int i,int j){return m.m[i*4+j];}
__device__ void mset(Mat4& m,int i,int j,float v){m.m[i*4+j]=v;}
__device__ float clampf(float x,float lo,float hi){return fminf(fmaxf(x,lo),hi);} 
__device__ float wrap_phi(float x){float y=fmodf(x,6.28318530718f);return y<0?y+6.28318530718f:y;}
__device__ Mat4 metric_contravariant(float r,float theta,float a){float ct=cosf(theta),st=sinf(theta),s2=fmaxf(st*st,1e-8f);float sig=r*r+a*a*ct*ct,dlt=r*r-2*r+a*a;float A=(r*r+a*a)*(r*r+a*a)-a*a*dlt*s2;Mat4 g={0};mset(g,0,0,-A/(sig*dlt));mset(g,0,3,-2*a*r/(sig*dlt));mset(g,3,0,mget(g,0,3));mset(g,1,1,dlt/sig);mset(g,2,2,1/sig);mset(g,3,3,(dlt-a*a*s2)/(sig*dlt*s2));return g;}
__device__ void metric_derivative_numeric(float r,float th,float a,Mat4& dr,Mat4& dth){float er=1e-3f,et=1e-4f;Mat4 gr0=metric_contravariant(r-er,th,a),gr1=metric_contravariant(r+er,th,a),gt0=metric_contravariant(r,th-et,a),gt1=metric_contravariant(r,th+et,a);for(int i=0;i<4;i++)for(int j=0;j<4;j++){mset(dr,i,j,(mget(gr1,i,j)-mget(gr0,i,j))/(2*er));mset(dth,i,j,(mget(gt1,i,j)-mget(gt0,i,j))/(2*et));}}
__device__ State6 kerr_rhs(State6 y,float p_t,float p_phi,float a){Mat4 g=metric_contravariant(y.r,y.th,a),dgdr,dgdth;metric_derivative_numeric(y.r,y.th,a,dgdr,dgdth);float p[4]={p_t,y.pr,y.pth,p_phi},xd[4]={0,0,0,0};for(int mu=0;mu<4;mu++)for(int nu=0;nu<4;nu++)xd[mu]+=mget(g,mu,nu)*p[nu];float pr=0,pth=0;for(int mu=0;mu<4;mu++)for(int nu=0;nu<4;nu++){pr+=-0.5f*p[mu]*mget(dgdr,mu,nu)*p[nu];pth+=-0.5f*p[mu]*mget(dgdth,mu,nu)*p[nu];}return {xd[0],xd[1],xd[2],xd[3],pr,pth};}
__device__ State6 rk2_geodesic_step(State6 y,float h,float p_t,float p_phi,float a){State6 k1=kerr_rhs(y,p_t,p_phi,a);State6 mid={y.t+.5f*h*k1.t,y.r+.5f*h*k1.r,y.th+.5f*h*k1.th,y.ph+.5f*h*k1.ph,y.pr+.5f*h*k1.pr,y.pth+.5f*h*k1.pth};State6 k2=kerr_rhs(mid,p_t,p_phi,a);return {y.t+h*k2.t,y.r+h*k2.r,clampf(y.th+h*k2.th,1e-6f,3.1415926f-1e-6f),y.ph+h*k2.ph,y.pr+h*k2.pr,y.pth+h*k2.pth};}
__device__ int cidx(int ir,int it,int ip,int c,int nt,int np){return (((ir*nt)+it)*np+ip)*11+c;}
__device__ int bracket_linear(const float* g,int n,float x,int& i0,int& i1,float& w){if(x<g[0]||x>g[n-1])return 0;int lo=0;while(lo<n-2&&g[lo+1]<=x)lo++;i0=lo;i1=lo+1;w=(x-g[i0])/fmaxf(g[i1]-g[i0],1e-20f);return 1;}
__device__ void bracket_phi(const float* g,int n,float ph,int& i0,int& i1,float& w){float p=wrap_phi(ph);int lo=0;while(lo<n-1&&g[lo+1]<=p)lo++;i0=lo;i1=(lo+1)%n;float hi=(i1>i0)?g[i1]:g[0]+6.28318530718f;float pp=(p>=g[i0])?p:p+6.28318530718f;w=(pp-g[i0])/fmaxf(hi-g[i0],1e-20f);}
__device__ void sample_brick_trilinear(const float* coeffs,const float* rg,const float* tg,const float* pg,int nr,int nt,int np,float r,float th,float ph,float outv[11]){int r0,r1,t0,t1,p0,p1;float wr,wt,wp;if(!bracket_linear(rg,nr,r,r0,r1,wr)||!bracket_linear(tg,nt,th,t0,t1,wt)){for(int c=0;c<11;c++)outv[c]=0;return;}bracket_phi(pg,np,ph,p0,p1,wp);for(int c=0;c<11;c++){float c000=coeffs[cidx(r0,t0,p0,c,nt,np)],c001=coeffs[cidx(r0,t0,p1,c,nt,np)],c010=coeffs[cidx(r0,t1,p0,c,nt,np)],c011=coeffs[cidx(r0,t1,p1,c,nt,np)],c100=coeffs[cidx(r1,t0,p0,c,nt,np)],c101=coeffs[cidx(r1,t0,p1,c,nt,np)],c110=coeffs[cidx(r1,t1,p0,c,nt,np)],c111=coeffs[cidx(r1,t1,p1,c,nt,np)];float c00=c000+wp*(c001-c000),c01=c010+wp*(c011-c010),c10=c100+wp*(c101-c100),c11=c110+wp*(c111-c110);outv[c]=(c00+wt*(c01-c00))+wr*((c10+wt*(c11-c10))-(c00+wt*(c01-c00)));}}
__device__ void rhs_stokes(const float S[4],const float c[11],float out[4]){out[0]=c[0]-(c[4]*S[0]+c[5]*S[1]+c[6]*S[2]+c[7]*S[3]);out[1]=c[1]-(c[5]*S[0]+c[4]*S[1]+c[8]*S[2]-c[9]*S[3]);out[2]=c[2]-(c[6]*S[0]-c[8]*S[1]+c[4]*S[2]+c[10]*S[3]);out[3]=c[3]-(c[7]*S[0]+c[9]*S[1]-c[10]*S[2]+c[4]*S[3]);}
__device__ void stokes_step_rk2(float S[4],const float c[11],float ds){float k1[4],mid[4],k2[4];rhs_stokes(S,c,k1);for(int i=0;i<4;i++)mid[i]=S[i]+0.5f*ds*k1[i];rhs_stokes(mid,c,k2);for(int i=0;i<4;i++)S[i]+=ds*k2[i];}
extern "C" __global__ void kerr_stokes_render_kernel(float* out_stokes,const float* coeffs,const float* r_grid,const float* theta_grid,const float* phi_grid,int width,int height,int nr,int nt,int np,float spin_a,int max_steps,float step){int x=blockIdx.x*blockDim.x+threadIdx.x,y=blockIdx.y*blockDim.y+threadIdx.y;if(x>=width||y>=height)return;int pix=y*width+x;float ndcx=2*((x+.5f)/width)-1,ndcy=1-2*((y+.5f)/height);State6 s={0,55,1.134464f,0,-1,-0.22f*ndcy};float p_t=-1,p_phi=0.12f*ndcx,S[4]={0,0,0,0};float rplus=1+sqrtf(fmaxf(1-spin_a*spin_a,0));for(int n=0;n<max_steps;n++){State6 prev=s;s=rk2_geodesic_step(s,step,p_t,p_phi,spin_a);float c[11];sample_brick_trilinear(coeffs,r_grid,theta_grid,phi_grid,nr,nt,np,.5f*(prev.r+s.r),.5f*(prev.th+s.th),.5f*(prev.ph+s.ph),c);float ds=sqrtf((s.r-prev.r)*(s.r-prev.r)+(s.th-prev.th)*(s.th-prev.th)+(s.ph-prev.ph)*(s.ph-prev.ph));stokes_step_rk2(S,c,ds);if(s.r<=rplus*1.0002f||s.r>220||!isfinite(s.r))break;}out_stokes[4*pix]=S[0];out_stokes[4*pix+1]=S[1];out_stokes[4*pix+2]=S[2];out_stokes[4*pix+3]=S[3];}
